<<<<<<< HEAD
/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RTOSDemo                               */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX231                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize su=0x300
=======
/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RTOSDemo                               */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX231                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize su=0x300
>>>>>>> 16c66438 (Upload from PC.)
#pragma stacksize si=0x300